resources:
  - https://github.com/fluxcd/image-reflector-controller/releases/download/v0.35.1/image-reflector-controller.crds.yaml
  - https://github.com/fluxcd/image-reflector-controller/releases/download/v0.35.1/image-reflector-controller.deployment.yaml
  - imagepolicy_editor_role.yaml
  - imagepolicy_viewer_role.yaml
  - imagerepository_editor_role.yaml
  - imagerepository_viewer_role.yaml
  - leader-election-role-binding.yaml
  - leader-election-role.yaml
  - role-binding.yaml
  - role.yaml

namespace: kommander-flux