apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - image-policy.yaml
  - image-repo.yaml
  - image-update-automation.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml

