resources:
  - https://raw.githubusercontent.com/gimlet-io/capacitor/main/deploy/k8s/rbac.yaml
  - https://raw.githubusercontent.com/gimlet-io/capacitor/main/deploy/k8s/manifest.yaml
  - ingress.yaml
  - networkpolicy.yaml

namespace: kommander-flux